[tool:pytest]
testpaths = src/tests
python_paths = src/app src/infra
addopts = --tb=short --strict-markers
markers = 
    unit: Unit tests
    integration: Integration tests
    slow: Slow tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning